# Generated by Django 4.1.2 on 2022-10-30 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0004_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericpage',
            name='author',
            field=models.ForeignKey(blank='False', null='True', on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='generic.author'),
            preserve_default='True',
        ),
    ]
